railsRent4Less/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  namespace :api, defaults:{format: :json} do
    # /api...
    namespace :v1 do 
      # /api/vi...
      resources :listings
      # /api/v1/listings
      resource :session, only: [:create, :destroy]
      resources :users, only: [:create] do
        # api/v1/user/current
        get :current, on: :collection
        # default
        # api/v1/user/:id/current
      end
    end
  end
  resources :users, only: [:new, :create,:show,:edit,:update]
  resource :session, only: [:new, :destroy, :create]
  get('/users/:id/edit_password', {to: 'users#edit_password', as: :edit_password_user})
  patch('/users/:id/update_password', {to: 'users#update_password', as: :update_password_user})
  # resources :addresses, only: [:new, :create,:index]
end

railsRent4Less/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentForCheap</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>


    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 100%;
      }
      /* Optional: Makes the sample page fill the window. */
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
    </style>
  </head>

  <body>
    
    <% if user_signed_in? %>
      Hello <%= current_user.full_name %>,
      <%= link_to "Logout", session_path, method: :delete, data: {confirm: "are you sure you want to log out?"}%>
    <% else %>
      <%= link_to "Login", new_session_path %> |
      <%= link_to "Sign Up", new_user_path %>
    <% end %>
    <hr>
    <%= flash.discard[:notice] || flash.discard[:alert] %>


    <%= yield %>
  </body>
</html>